apiVersion: v1
kind: Service
metadata:
  name: authservice-nodeport-service
spec:
  type: NodePort
  selector:
    app: authservice
  ports:
  - name: authservice
    protocol: TCP
    port: 3001
    targetPort: 3001
