apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventbus
  template:
    metadata:
      labels:
        app: eventbus
    spec:
      containers:
      - name: eventbus
        image: cesarfkb/eventbus
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: eventbus-service
spec:
  selector:
    app: eventbus
  type: ClusterIP
  ports:
  - name: eventbus
    protocol: TCP
    port: 3003
    targetPort: 3003
