apiVersion: v1
kind: Service
metadata:
  name: playerservice-service
spec:
  type: NodePort
  selector:
    app: playerservice
  ports:
  - name: playerservice
    protocol: TCP
    port: 3002
    targetPort: 3002
